version: "2.1"
services:
  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - 1080:80
      - "25:25"
  app:
    build: .
    volumes:
      - .:/app
      - ~/.ssh/:/root/.ssh/
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - 4000:3000
    environment:
      - RAILS_ENV=development

  postgres:
    image: postgres:9.6.5-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=gamifiedworkplace_development
    ports:
      - "6000:5432"

  redis:
    image: redis:5.0-rc3-alpine

networks:
  default:
    external: true
    name: dev
